# Generated by Django 5.0.7 on 2024-08-06 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_cart_wishlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Watches',
            new_name='Watchess',
        ),
    ]
