# Generated by Django 5.0.7 on 2024-08-06 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_rename_watches_watchess'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Watchess',
            new_name='Watches',
        ),
    ]
